#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: Qodana

on:
  workflow_dispatch:
  pull_request:

  push:
    branches-ignore:
      - "gh-pages"

jobs:
  qodana:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

        with:
          package_json_file: modules/web/web-core/web-frontend/package.json
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4

        with:
          node-version-file: modules/web/web-core/web-frontend/package.json
          cache-dependency-path: modules/web/web-core/web-frontend/pnpm-lock.yaml
          cache: "pnpm"

      - name: Install Node packages
        run: "pnpm -C modules/web/web-core/web-frontend install"

      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2025.1

        timeout-minutes: 60

        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: "https://qodana.cloud"

        with:
          # In pr-mode: 'true' Qodana checks only changed files
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true

          # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
          upload-result: false

          # quick-fixes available in Ultimate and Ultimate Plus plans
          push-fixes: "none"

          args: "--property,project.open.type=Gradle"

      - uses: actions/upload-artifact@v4
        if: always()

        with:
          name: qodana-artifact
          path: ${{ runner.temp }}/qodana/results
